---
RNG_SEED: -1
GPUS: '0,1,2,3,4,5,6,7'
NUM_WORKERS_PER_GPU: 1
RUN: 'fully_conv_transformer_ac'
OUTPUT_PATH: 'outputs/'
MODEL: 'resnet18_transformer'
TASK_TYPE: 'Classification'

DATASET:
    DATASET_NAME: 'kinetics'
    DATA_PATH: '/data/datasets/kinetics700_2020/'
    TRAIN_ANNOTATIONS_PATH: 'full/train.json' 
    VAL_ANNOTATIONS_PATH: 'full/val.json'
    CLASS_TO_INDEX_FILE: 'full/class_to_index.json'
    TRAIN_VIDEO_RESIZED_PATH: 'train_cache'
    VAL_VIDEO_RESIZED_PATH: 'val_cache'
    TOY: False
    TOY_SAMPLES: 100
    SAMPLING_STRIDE: 2
    TRAIN_SPLIT: 'train'
    VAL_SPLIT: 'val'


NETWORK:
    BACKBONE_LOAD_PRETRAINED: True
    NUM_CLASSES: 700
    PARTIAL_PRETRAIN: False
    PRETRAINED_MODEL: ''

    RETURN_ALL_FEATURES: False
    TSA_EVERY_BLOCK: True
    IMAGE_SPAT_DIMENSION:
        - 3
        - 224
        - 224
    FINAL_MLP_HIDDEN: 1024
    FINAL_MLP_DROPOUT: 0.5

    TSA:
        ATTENTION_DROPOUT: 0.1

TRAIN:
    BATCH_SIZE: 8
    LR: 0.0001
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.01
    OPTIMIZER: 'AdamW'
    SHUFFLE: True
    BEGIN_EPOCH: 0
    END_EPOCH: 10

VAL:
    BATCH_SIZE: 8
    SHUFFLE: False
